Added raw data files and documentation on method for grouping
ubsuny/CP1-24-HW4 pull request #16
Opened 2024-10-27 23:47 UTC by iglesias-cardinale

# Added two folders

1) ## Data
### Added three raw data files:

- ```raw_data_table1.md``` is the data from table one in Hubble's paper.
- ```raw_data_table1_grouped.md``` is the data from table one in Hubble's paper sorted based on the first column.
- ```raw_data_table2.md``` is the data from table two in Hubble's paper. This one isn't particularly useful.
- 
### Added plotting code

- ```data_plotter.ipynb``` was used to plot the data to make sure the grouping was done correctly. It could also be built upon to add the curve fitting later.

2) ## Doumentation

- ```group_selection.md``` gives motivation and methods for grouping the data
- ```reproduced_figure1.png``` is a figure produced in ```data_plotter.ipynb```  that recreates the data display in figure 1 of Hubble's paper

2024-10-28 04:50 UTC, avgagliardo commented
I'll request to review this code for tomorrow if no one else is in line for it.

2024-10-28 08:14 UTC, HeshamElsaman commented
@avgagliardo great, I assigned it to you to review then.

2024-10-28 22:32 UTC, avgagliardo commented on Data/data_plotter.ipynb
Reviewed, but I'll assume this is just a temporary workspace and not a file meant to be pushed

2024-10-28 22:34 UTC, avgagliardo commented on Data/raw_data_table1.md
Not rendering as a table

2024-10-28 22:34 UTC, avgagliardo commented on Data/raw_data_table1_grouped.md
Not rendering as a table

2024-10-28 22:35 UTC, avgagliardo commented on Data/raw_data_table2.md
Not rendering as a table

2024-10-28 22:37 UTC, avgagliardo commented on Documentation/group_selection.md
looks good in terms of markdown rendering, but the link to https://github.com/ubsuny/CP1-24-HW4/blob/a04b0d2dc5e79a131f9ce6c6131e630f79c13ae6/workspaces/CP1-24-HW4/Data/raw_data_table1_grouped.md throws a 404 so either the file is not located at the location (sometimes the case for temporary files that may have moved), or perhaps the url is malformed.

2024-10-28 22:37 UTC, avgagliardo commented on Documentation/reproduced_figure1.png
looks great

2024-10-28 22:39 UTC, avgagliardo requested changes
For now I will politely request the following changes:
- PR has several tables that are not rendering as proper markdown. 
- The following URL is nonfunctional: https://github.com/ubsuny/CP1-24-HW4/blob/a04b0d2dc5e79a131f9ce6c6131e630f79c13ae6/workspaces/CP1-24-HW4/Data/raw_data_table1_grouped.md

Otherwise the plot and doc look good, great work!

2024-10-31 05:49 UTC, avgagliardo commented
@iglesias-cardinale let me know when you want me to review this again. I am doing my best to watch for it.

2024-10-31 16:07 UTC, iglesias-cardinale commented on Data/data_plotter.ipynb
No, it doesn't need to be pushed. But I'm not sure how to remove it from the pull request.

2024-10-31 16:09 UTC, iglesias-cardinale commented on Data/raw_data_table1.md
The intention for the md files wasn't to render as tables. They were just presenting the data from table 1 of the paper, table 2 of the paper, and a grouped/organized version of table 1. I can see how the naming convention is misleading. They're actually specifically organized to be callable by np.loadtxt, so not sure if I should change these.

2024-10-31 23:09 UTC, avgagliardo commented
Not sure if this is ready yet, but ill give it another review in about 30-60 mins (just in case)

2024-11-01 00:34 UTC, avgagliardo commented on Data/data_plotter.ipynb
[Here](https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request) is an example for removing files, but its probably okay for now. 

If you want to delete it after the merge and do another PR, that works too. I'll just push this one for now so it doesn't hold things up.

2024-11-01 00:35 UTC, avgagliardo commented on Data/raw_data_table1.md
If its not supposed to be rendered as markdown, I would consider naming it as a .txt file for clarity but its okay now that I know its not supposed to be rendered as a table

2024-11-01 00:36 UTC, avgagliardo approved these changes
Changes look good, approving for merge

2024-11-01 02:35 UTC, HeshamElsaman commented
Great, merging.

2024-11-01 02:35 UTC, merged